export const siemensPortfolioOptions = [
  'Insights Hub',
  'Mendix',
  'Industrial Edge',
  'Industrial AI Suite',
  'Senseye Predictive Maintenance',
  'Teamcenter',
  'Teamcenter X',
  'Teamcenter Quality',
  'Polarion',
  'gPROMS Process',
  'Simcenter Flomaster',
  'SIMIT',
  'Simcenter STAR-CCM+',
  'COMOS',
  'XHQ',
  'Opcenter',
  'Opcenter Intelligence',
  'NX / Designcenter',
  'Tecnomatix / Process Simulate',
  'Capital',
]
